name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_API_NAME}}
          heroku_email: ${{secrets.HEROKU_API_EMAIL}}
          buildpack: ${{secrets.HEROKU_API_GIT}}
